<?php

namespace App\Http\Controllers;

use App\Models\Submission;
use App\Services\PdfGenerationService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CertificateController extends Controller
{
    public function __construct(
        private readonly PdfGenerationService $pdfService
    ) {}

    /**
     * GET /verify/{ref}
     *
     * Public endpoint — anyone can verify a certificate's authenticity.
     * Returns JSON (API) or a rendered HTML page depending on Accept header.
     * No authentication required.
     */
    public function verify(string $ref): JsonResponse
    {
        $submission = Submission::with(['formType', 'student', 'department'])
            ->where('reference_no', $ref)
            ->whereNotNull('output_document')
            ->first();

        if (!$submission) {
            return response()->json([
                'valid'   => false,
                'message' => 'No verified document found for the provided reference number.',
            ], 404);
        }

        // Return only what an external verifier needs — never expose full form data
        return response()->json([
            'valid'        => true,
            'reference_no' => $submission->reference_no,
            'document_type'=> $submission->formType->name,
            'student_name' => $submission->is_anonymous ? 'Confidential' : $submission->student?->name,
            'student_id'   => $submission->is_anonymous ? 'Confidential' : $submission->student?->student_id,
            'issued_by'    => $submission->department->name . ', Daffodil International University',
            'issued_on'    => $submission->resolved_at?->format('d F Y'),
            'status'       => $submission->status->label(),
            'message'      => 'This document has been verified as authentic.',
        ]);
    }

    /**
     * GET /student/submissions/{ref}/download
     *
     * Authenticated student route — guarded by a signed URL.
     * The signed URL is generated by PdfGenerationService::signedDownloadUrl()
     * and expires after 30 minutes.
     */
    public function download(Request $request, string $ref)
    {
        // Laravel validates the signed URL automatically via the signed middleware
        if (!$request->hasValidSignature()) {
            abort(403, 'This download link has expired. Please generate a new one from your submissions page.');
        }

        $submission = Submission::with('formType')
            ->where('reference_no', $ref)
            ->whereNotNull('output_document')
            ->first();

        if (!$submission) {
            abort(404, 'Document not found.');
        }

        // Ensure the authenticated user owns this submission
        if ($request->user() && $submission->student_id !== $request->user()->id) {
            abort(403);
        }

        return $this->pdfService->streamPdf($submission);
    }

    /**
     * POST /student/submissions/{ref}/download-link
     *
     * Generates and returns a fresh signed download URL.
     * Students call this to get a time-limited URL before downloading.
     */
    public function generateDownloadLink(Request $request, string $ref): JsonResponse
    {
        $submission = Submission::where('reference_no', $ref)
            ->where('student_id', $request->user()->id)
            ->whereNotNull('output_document')
            ->firstOrFail();

        return response()->json([
            'download_url' => $this->pdfService->signedDownloadUrl($submission),
            'expires_in'   => '30 minutes',
        ]);
    }
}
